# Generated by Django 4.1.7 on 2023-04-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Data",
        ),
    ]
